# 自定义starter配置
com:
  www:
    ledger:
      pdd-head-map:  {ORDER_ID: 订单号,ORDER_DATE: 订单成交时间,GOODS_ID: 商品id,GOODS_NAME: 商品,ORDER_STATE: 订单状态,SALE_AMOUNT: 商品总价(元),PAYMENT_AMOUNT: 商家实收金额(元),REMARK: 商家备注}
      taobao-head-map: {ORDER_ID: 订单编号,ORDER_DATE: 订单创建时间,GOODS_NAME: 宝贝标题,ORDER_STATE: 订单状态,SALE_AMOUNT: 总金额,PAYMENT_AMOUNT: 买家实际支付金额,REMARK: 订单备注}
    common:
      code:
        write-enable: true
        code-redis-key: ledger:code:code_data:code_type
#服务器配置
server:
  servlet:
    #访问路径设置
    context-path: /
spring:
  profiles:
    #配置环境文件
    active: @profileActive@
  application:
    name: ledger-system
  # 返回报文json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #配置返回日期格式
    time-zone: GMT+8 #配置时间区
    default-property-inclusion: non_empty #非空属性才返回
#mybatis配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实现数据库下划线字段到POJO类驼峰形式的自动映射
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: ignored #字段更新忽略null判断