-- 数据字典数据
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('Sex', '性别', 'K1', '1', '男', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('Sex', '性别', 'K0', '0', '女', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('UserState', '用户状态', 'K1', '1', '有效', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('UserState', '用户状态', 'K2', '2', '注销', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('UserState', '用户状态', 'K3', '3', '封号', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('YesOrNo', '是否', 'K1', '1', '是', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('YesOrNo', '是否', 'K0', '0', '否', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('ShopPlatform', '店铺平台', 'K1', '1', '拼多多', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('ShopPlatform', '店铺平台', 'K2', '2', '淘宝', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('ShopState', '店铺状态', 'K1', '1', '有效', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('ShopState', '店铺状态', 'K0', '0', '注销', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K0', '0', '待确认', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K1', '1', '未支付，交易关闭', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K2', '2', '未发货，退款成功', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K3', '3', '已发货，待签收', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K4', '4', '交易成功', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K5', '5', '退货退款', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K6', '6', '仅退款', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K7', '7', '刷单', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K8', '8', '待发货', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K9', '9', '待申请退款', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('OrderState', '订单状态', 'K10', '10', '待支付', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('PayType', '支出类型', 'K1', '1', '推广费', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('PayType', '支出类型', 'K2', '2', '服务费', '1');
INSERT INTO `CODE_DATA` (`CODE_TYPE`, `CODE_NAME`, `CODE_KEY`, `CODE_VALUE`, `VALUE_NAME`, `IS_VALID`) VALUES ('PayType', '支出类型', 'K3', '3', '店铺保证金', '1');
-- 角色信息
INSERT INTO `SYS_ROLE` (`ROLE_CODE`, `ROLE_NAME`, `UPDATE_TIME`, `CREATE_TIME`) VALUES ('ROLE_USER', '普通用户', now(), now());
-- 角色访问权限信息
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/user/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/code/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/book/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/shop/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/year/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/month/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/day/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/order/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`)
VALUES ('/pay/*', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'));
-- 角色路由信息
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/book', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/shop', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/year', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/month', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/day', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/order', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');
INSERT INTO `AUTHORITY_ROLE` (`URL`, `ROLE_ID`, `URL_TYPE`)
VALUES ('/pay', (SELECT R.ROLE_ID FROM SYS_ROLE R WHERE R.ROLE_CODE='ROLE_USER'),'2');